name: Publish Docs

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
      FRED_KEY: ${{ secrets.FRED_KEY }} 

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test
    - name: build docs
      run: dotnet fsdocs build --eval --clean --properties Configuration=Release
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Examine docs output
      run: ls -r output 
    - name: Pack nuget
      run: dotnet pack -c Release
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push src/FSharp.Data.Fred/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }} --skip-duplicate
