name: Publish Docs

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
      FRED_KEY: ${{ secrets.FRED_KEY }} 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Build and test
      run: dotnet fake build -t All
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Examine artifacts
      run: ls -r artifacts
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push artifacts/FSharp.Data.Fred.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }} --skip-duplicate
